<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite guice-stage="DEVELOPMENT" name="Failed suite [SuiteAcademico]">
  <test thread-count="5" name="Tests.VerifyForm_Mensaje-Error_CodigoSis-Vacio(failed)">
    <classes>
      <class name="Tests.VerifyForm_4">
        <methods>
          <include name="setup"/>
          <include name="verifyCorrectForm"/>
          <include name="quit"/>
        </methods>
      </class> <!-- Tests.VerifyForm_4 -->
    </classes>
  </test> <!-- Tests.VerifyForm_Mensaje-Error_CodigoSis-Vacio(failed) -->
  <test thread-count="5" name="Tests.VerifyForm_Mensaje-Error_Telefono-Vacio(failed)">
    <classes>
      <class name="Tests.VerifyForm_5">
        <methods>
          <include name="verifyCorrectForm"/>
          <include name="setup"/>
          <include name="quit"/>
        </methods>
      </class> <!-- Tests.VerifyForm_5 -->
    </classes>
  </test> <!-- Tests.VerifyForm_Mensaje-Error_Telefono-Vacio(failed) -->
</suite> <!-- Failed suite [SuiteAcademico] -->
